import { expect, test } from "@playwright/test";

test("turn navigation preserves drafts and explains the technician to inspector handoff", async ({ page }, testInfo) => {
  test.setTimeout(90000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const session = await (await page.request.get("/api/auth/me")).json();
  const headers = { "x-csrf-token": session.csrfToken };
  const post = async (path: string, data: unknown) => {
    const response = await page.request.post(`/api${path}`, { headers, data });
    expect(response.ok(), await response.text()).toBeTruthy();
    return response.json();
  };
  const { property } = await post("/operations/properties", { code: `UX${Date.now()}`, name: "Usability fixture" });
  const { unit } = await post("/operations/units", { propertyId: property.id, number: "UX-1" });
  const meta = await (await page.request.get("/api/meta")).json();
  const section = meta.boardSections.find((row: any) => row.propertyId === property.id && row.sectionType === "MAKE_READY");
  const item = await post("/make-ready-items", { propertyId: property.id, unitId: unit.id, boardGroup: section.key, itemName: unit.number, unitNumber: unit.number, vacancyStatus: "VACANT NOT LEASED NOT READY", completionStatus: "NO" });
  await page.reload();
  await page.getByTestId("property-filter").selectOption(property.id);
  await page.getByRole("button", { name: `Open details for ${unit.number}`, exact: true }).click();
  await expect(page.getByTestId("drawer-pane-work")).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByTestId("drawer-risk-section")).toBeHidden();
  const notes = page.getByTestId("unit-work-notes").getByRole("textbox");
  await page.getByRole("button", { name: "Parts & work notes", exact: true }).click();
  await notes.fill("Replace damaged cabinet faces from stock.");
  await page.getByTestId("quick-materials").getByLabel("Part 1", { exact: true }).fill("Filter");
  await page.getByTestId("drawer-pane-notes").click();
  await expect(page.getByTestId("drawer-notes-section")).toBeVisible();
  await page.getByRole("button", { name: "work notes in Work & parts" }).click();
  await expect(notes).toBeFocused();
  await expect(notes).toHaveValue("Replace damaged cabinet faces from stock.");
  await page.getByTestId("drawer-pane-photos").click();
  await expect(page.getByTestId("drawer-attachments")).toBeVisible();
  await page.getByTestId("drawer-pane-work").click();
  await expect(page.getByTestId("quick-materials").getByLabel("Part 1", { exact: true })).toHaveValue("Filter");
  await page.getByRole("button", { name: "Preparation checks", exact: true }).click();
  await expect(page.getByTestId("technician-preparation-checks").locator("select").first()).toBeFocused();
  await page.getByRole("button", { name: "Resident codes", exact: true }).click();
  await expect(page.getByRole("button", { name: "Show codes", exact: true })).toBeFocused();

  for (const width of [390, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await page.getByTestId("drawer-pane-work").click();
    const help = page.getByRole("button", { name: "Help with the turn process", exact: true });
    await help.click();
    await expect(page.getByRole("tooltip")).toContainText("Repairs finished is not the same as unit ready");
    await expect(page.getByRole("tooltip")).toBeInViewport();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("tooltip")).toHaveCount(0);
    await expect(page.getByTestId("item-drawer")).toBeVisible();
    await page.getByTestId("drawer-pane-work").focus();
    await page.mouse.move(0, 0);
    await help.hover();
    await expect(page.getByRole("tooltip")).toBeVisible();
    await page.mouse.move(0, 0);
    await expect(page.getByRole("tooltip")).toHaveCount(0);
    await help.focus();
    await expect(page.getByRole("tooltip")).toBeVisible();
    await page.keyboard.press("Escape");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  }
  await page.getByTestId("item-drawer").screenshot({ path: testInfo.outputPath("turn-work-desktop.png") });
  await page.getByTestId("drawer-pane-all").click();
  await expect(page.getByTestId("drawer-field-assignedTech")).toBeVisible();
  await expect(notes).toHaveValue("Replace damaged cabinet faces from stock.");
  await page.getByTestId("unit-work-notes").getByRole("button", { name: "Save work notes", exact: true }).click();
  await expect(page.getByTestId("unit-work-notes")).toContainText("Work notes saved");
  await page.getByTestId("quick-materials").getByRole("button", { name: "Save parts list", exact: true }).click();
  await expect(page.getByTestId("quick-materials")).toContainText("Parts list saved");
  await page.getByTestId("item-drawer-close").click();
  await page.screenshot({ path: testInfo.outputPath("turn-board-desktop.png") });
  await page.keyboard.press("Control+k");
  await page.getByTestId("command-search").fill("cabinet");
  await expect(page.getByTestId("command-palette")).toContainText("Work & parts for tasks");
  await page.keyboard.press("Escape");

  expect((await page.request.patch(`/api/make-ready-items/${item.id}`, { headers, data: { makeReadyStatus: "DONE", paintStatus: "DONE", cleaningStatus: "DONE" } })).ok()).toBeTruthy();
  const path = `/api/make-ready-items/${item.id}/final-walk`;
  const actual = await (await page.request.get(path)).json();
  let assignment: any = null;
  let fail = false;
  await page.route(`**${path}`, route => fail ? route.fulfill({ status: 403, json: { message: "Assignment unavailable" } }) : route.fulfill({ json: { ...actual, block: assignment, blockers: ["Fixture: order is awaiting delivery"] } }));
  await page.reload();
  await page.getByRole("button", { name: `Open details for ${unit.number}`, exact: true }).click();
  await expect(page.getByTestId("drawer-pane-final")).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByTestId("turn-readiness-blockers")).toContainText("Fixture: order is awaiting delivery");
  await expect(page.locator(".completion-ready")).toHaveCount(0);
  await page.getByTestId("drawer-pane-work").click();
  await expect(page.getByTestId("turn-handoff-summary")).toContainText("Final walk needs an inspector");
  assignment = { id: "fixture-block", assignedUserId: "fixture-inspector", assignedUser: { fullName: "Fixture inspector" }, plannedDate: "2030-01-02" };
  await page.getByRole("button", { name: "Open final walk & blockers", exact: true }).click();
  await page.getByRole("button", { name: "Recheck completion blockers", exact: true }).click();
  await expect(page.getByTestId("final-walk-controls")).toContainText("Fixture inspector");
  await page.getByTestId("drawer-pane-work").click();
  await expect(page.getByTestId("turn-handoff-summary")).toContainText("Next: Fixture inspector - final walk");
  await expect(page.getByTestId("turn-handoff-summary")).toContainText("No separate send action");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByTestId("drawer-pane-work").click();
  await page.getByTestId("item-drawer").screenshot({ path: testInfo.outputPath("turn-handoff-mobile.png") });
  fail = true;
  await page.getByRole("button", { name: "Open final walk & blockers", exact: true }).click();
  await page.getByRole("button", { name: "Recheck completion blockers", exact: true }).click();
  await expect(page.getByTestId("final-walk-controls")).toContainText("Could not load final walk assignment");
  await expect(page.getByTestId("final-walk-controls")).not.toContainText("Fixture inspector");
  await page.getByTestId("drawer-pane-work").click();
  await expect(page.getByTestId("turn-handoff-summary")).toContainText("could not be verified");
  await expect(page.getByTestId("turn-handoff-summary")).not.toContainText("Fixture inspector");
});
