import { expect, test } from "@playwright/test";

test("parts conflict review retains mobile additions and avoids lost-response duplicates", async ({ page }, testInfo) => {
  test.setTimeout(90000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const session = await (await page.request.get("/api/auth/me")).json();
  const headers = { "x-csrf-token": session.csrfToken };
  const post = async (path: string, data: unknown) => {
    const response = await page.request.post(`/api${path}`, { headers, data });
    expect(response.ok(), await response.text()).toBeTruthy();
    return response.json();
  };
  const { property } = await post("/operations/properties", { code: `PART${Date.now()}`, name: "Parts recovery fixture" });
  const meta = await (await page.request.get("/api/meta")).json();
  const section = meta.boardSections.find((entry: any) => entry.propertyId === property.id && entry.sectionType === "MAKE_READY");
  const { unit } = await post("/operations/units", { propertyId: property.id, number: "PARTS-1" });
  const item = await post("/make-ready-items", { propertyId: property.id, unitId: unit.id, boardGroup: section.key, itemName: unit.number, unitNumber: unit.number, vacancyStatus: "VACANT NOT LEASED NOT READY", completionStatus: "NO" });
  const root = `/api/make-ready-items/${item.id}/materials`;
  await page.reload();
  await page.getByTestId("property-filter").selectOption(property.id);
  await page.getByRole("button", { name: `Open details for ${unit.number}`, exact: true }).click();
  const entry = page.getByTestId("quick-materials");
  await entry.getByLabel("Part 1", { exact: true }).fill("Technician filter");
  const teammate = { id: "00000000-0000-4000-8000-000000000001", name: "Manager order", quantity: 2, unit: "each", status: "ORDERED", notes: "Keep this order" };
  expect((await page.request.put(root, { headers, data: { version: 0, rows: [teammate] } })).ok()).toBeTruthy();
  await entry.getByRole("button", { name: "Save parts list", exact: true }).click();
  await expect(entry.getByRole("alert")).toContainText("changed in another session");
  await entry.getByRole("button", { name: "Review latest list", exact: true }).click();
  await expect(entry.getByTestId("material-conflict-review")).toContainText("1 saved line / 1 new line to keep / 0 already saved");
  await entry.getByText("Latest saved parts", { exact: true }).click();
  await expect(entry).toContainText("Manager order: 2 each (ordered)");
  await entry.getByRole("button", { name: "Keep my lines with the latest list", exact: true }).click();
  expect((await (await page.request.get(root)).json()).version).toBe(1);
  await page.reload();
  await expect(page.getByTestId("item-drawer")).toBeVisible();
  await expect(entry.getByLabel("Part 1", { exact: true })).toHaveValue("Technician filter");
  await entry.getByRole("button", { name: "Save parts list", exact: true }).click();
  await expect(entry).toContainText("Parts list saved to the team list");
  const merged = await (await page.request.get(root)).json();
  expect(merged.version).toBe(2);
  expect(merged.rows).toHaveLength(2);
  expect(merged.rows[0]).toEqual(teammate);
  expect(merged.rows[1].name).toBe("Technician filter");

  await entry.getByLabel("Part 1", { exact: true }).fill("Paint");
  await page.route(`**${root}`, async route => {
    if (route.request().method() !== "PUT") return route.continue();
    const saved = await route.fetch();
    expect(saved.ok(), await saved.text()).toBeTruthy();
    await route.fulfill({ status: 503, json: { message: "Response lost after saving" } });
  });
  await entry.getByRole("button", { name: "Save parts list", exact: true }).click();
  await expect(entry.getByRole("alert")).toContainText("Response lost after saving");
  await page.unroute(`**${root}`);
  await entry.getByRole("button", { name: "Save parts list", exact: true }).click();
  await expect(entry.getByRole("alert")).toContainText("changed in another session");
  await entry.getByRole("button", { name: "Review latest list", exact: true }).click();
  await expect(entry.getByTestId("material-conflict-review")).toContainText("3 saved lines / 0 new lines to keep / 1 already saved");
  await page.setViewportSize({ width: 1440, height: 900 });
  await entry.getByRole("button", { name: "Use latest saved list", exact: true }).click();
  await expect(entry.getByRole("button", { name: "Save parts list", exact: true })).toBeDisabled();
  await expect(entry).toContainText("Parts list saved to the team list");
  const recovered = await (await page.request.get(root)).json();
  expect(recovered.version).toBe(3);
  expect(recovered.rows.filter((row: any) => row.name === "Paint")).toHaveLength(1);
  expect(recovered.rows[0]).toEqual(teammate);

  await page.setViewportSize({ width: 390, height: 844 });
  const panel = page.getByTestId("turn-materials");
  await panel.getByRole("button", { name: "Edit Technician filter", exact: true }).click();
  const editor = page.getByTestId("turn-material-editor");
  await editor.getByLabel("Notes / supplier / order reference").fill("Tech supplier note");
  const changedOrder = { ...teammate, notes: "Manager updated delivery" };
  expect((await page.request.put(root, { headers, data: { version: 3, rows: recovered.rows.map((row: any) => row.id === teammate.id ? changedOrder : row) } })).ok()).toBeTruthy();
  await editor.getByRole("button", { name: "Save material", exact: true }).click();
  await expect(editor.getByRole("alert")).toContainText("changed in another session");
  await editor.getByRole("button", { name: "Review latest parts list", exact: true }).click();
  await expect(editor.getByTestId("material-edit-review")).toContainText("This line has not changed on the server");
  await editor.getByRole("button", { name: "Keep my edits with latest list", exact: true }).click();
  expect((await (await page.request.get(root)).json()).version).toBe(4);
  await expect(editor.getByLabel("Notes / supplier / order reference")).toHaveValue("Tech supplier note");
  await editor.getByRole("button", { name: "Save material", exact: true }).click();
  await expect(editor).not.toBeVisible();
  const edited = await (await page.request.get(root)).json();
  expect(edited.version).toBe(5);
  expect(edited.rows[0]).toEqual(changedOrder);
  expect(edited.rows[1].notes).toBe("Tech supplier note");
  await panel.getByRole("button", { name: "Edit Technician filter", exact: true }).click();
  await editor.getByLabel("Quantity", { exact: true }).fill("3");
  expect((await page.request.put(root, { headers, data: { version: 5, rows: edited.rows.map((row: any) => row.id === edited.rows[1].id ? { ...row, quantity: 4 } : row) } })).ok()).toBeTruthy();
  await editor.getByRole("button", { name: "Save material", exact: true }).click();
  await editor.getByRole("button", { name: "Review latest parts list", exact: true }).click();
  await expect(editor.getByRole("alert")).toContainText("Someone changed this same parts line");
  await expect(editor.getByTestId("material-edit-review")).toHaveCount(0);
  await expect(editor.getByLabel("Quantity", { exact: true })).toHaveValue("3");
  const conflict = await (await page.request.get(root)).json();
  expect(conflict.version).toBe(6);
  expect(conflict.rows[1].quantity).toBe(4);
  page.once("dialog", dialog => dialog.accept());
  await editor.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(editor).not.toBeVisible();
  const part = panel.getByTestId(`material-${edited.rows[1].id}`);
  const collected = part.getByRole("checkbox", { name: "Collected Technician filter", exact: true });
  await collected.click();
  await expect(part.locator(".material-collected")).toHaveText("Technician filter");
  await expect(part.getByRole("combobox")).toHaveValue("ON_HAND");
  expect((await (await page.request.get(root)).json()).rows[1].status).toBe("ON_HAND");
  await page.reload();
  await expect(collected).toBeChecked();
  await collected.click();
  await expect(part.getByRole("combobox")).toHaveValue("NEEDED");
  await expect(part.locator(".material-collected")).toHaveCount(0);
  await part.getByRole("combobox").selectOption("NEED_TO_ORDER");
  await expect(panel.getByRole("status", { exact: false }).filter({ hasText: "Need to order saved" })).toBeVisible();
  await part.getByRole("combobox").selectOption("ORDERED");
  await expect(panel.getByRole("status", { exact: false }).filter({ hasText: "On order saved" })).toBeVisible();
  await expect(collected).not.toBeChecked();
  await page.route(`**${root}`, route => route.request().method() === "PUT" ? route.fulfill({ status: 503, json: { message: "Save failed" } }) : route.continue());
  await collected.click();
  await expect(panel.getByRole("alert")).toContainText("Could not confirm");
  await expect(collected).not.toBeChecked();
  await expect(part.locator(".material-collected")).toHaveCount(0);
  await page.unroute(`**${root}`);
  const latest = await (await page.request.get(root)).json();
  expect((await page.request.put(root, { headers, data: { version: latest.version, rows: latest.rows.map((row: any) => row.id === edited.rows[1].id ? { ...row, notes: "Another technician's update" } : row) } })).ok()).toBeTruthy();
  await collected.click();
  await expect(panel.getByRole("alert")).toContainText("The parts list changed");
  await expect(collected).not.toBeChecked();
  await panel.getByRole("button", { name: "Refresh parts list", exact: true }).click();
  await expect(part).toContainText("Another technician's update");
  await collected.click();
  await expect(part.locator(".material-collected")).toBeVisible();
  await part.screenshot({ path: testInfo.outputPath("collected-part-mobile.png") });
  await part.getByRole("combobox").selectOption("USED");
  await expect(collected).toBeDisabled();
  await expect(collected).toBeChecked();
  await part.getByRole("combobox").selectOption("CANCELLED");
  await expect(collected).toBeDisabled();
  await expect(collected).not.toBeChecked();
  await expect(part.locator(".material-collected")).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
