import { expect, test } from "@playwright/test";

test("stock inspection defaults today's date and defers move-in handoff", async ({ page }) => {
  test.setTimeout(90000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const headers = { "x-csrf-token": (await (await page.request.get("/api/auth/me")).json()).csrfToken };
  const send = async (method: string, path: string, data: unknown) => {
    const response = await page.request.fetch(`/api${path}`, { method, headers, data });
    expect(response.ok(), await response.text()).toBe(true);
    return response.json();
  };
  const { property } = await send("POST", "/operations/properties", { code: `STOCK${Date.now()}`, name: "Stock inspection demo" });
  const meta = await (await page.request.get("/api/meta")).json();
  const boardGroup = meta.boardSections.find((s: any) => s.propertyId === property.id && s.sectionType === "MAKE_READY").key;
  const item = await send("POST", "/make-ready-items", { propertyId: property.id, unitNumber: "STOCK-101", itemName: "STOCK-101", boardGroup, vacancyStatus: "VACANT NOT LEASED NOT READY" });
  const itemPath = `/make-ready-items/${item.id}`;
  const reportPath = `/final-walk-reports/${property.id}`;
  const prep = await (await page.request.get(`/api${itemPath}/resident-codes`)).json();
  await send("PUT", `${itemPath}/resident-codes`, { version: prep.version, value: { technicianResults: Object.fromEntries(prep.technicianChecks.map((check: any) => [check.id, { status: "CHECKED", note: "" }])) } });
  await send("PATCH", itemPath, { makeReadyStatus: "DONE", paintStatus: "DONE", cleaningStatus: "DONE" });
  await page.reload();
  await page.getByTestId("property-filter").selectOption(property.id);
  await page.getByRole("button", { name: /View:/ }).click();
  await page.getByTestId("tab-table").click();
  await page.getByTestId("mobile-details-stock-101").click();
  await page.getByRole("button", { name: "Inspection details / report", exact: true }).click();
  const report = page.getByTestId("final-report-editor");
  const today = await page.evaluate(() => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; });
  await expect(report.getByTestId("final-report-date")).toHaveValue(today);
  await expect(report.getByTestId("stock-inspection-notice")).toBeVisible();
  await expect(report.locator('[data-testid^="final-report-result-"]')).toHaveCount(8);
  await expect(report.getByLabel("Resident gate code", { exact: true })).not.toBeVisible();
  for (const select of await report.locator('[data-testid^="final-report-result-"]').all()) await select.selectOption("CHECKED");
  await report.getByTestId("final-report-save-draft").click();
  await expect(report.getByTestId("final-report-save-draft")).toBeDisabled();
  const saved = await (await page.request.get(`/api${reportPath}?itemId=${item.id}`)).json();
  expect(saved.draft.value).toMatchObject({ inspectionDate: today, handoffConfirmed: false, fobs: "" });
  expect(saved.draft.value.results["handoff-v2-2"]).toBeUndefined();
  const preview = await send("POST", `${reportPath}/preview`, { itemId: item.id, settings: saved.settings.value, draft: saved.draft.value, format: "html" });
  expect(preview.html).toContain("Stock-ready inspection / no move-in scheduled.");
  expect(preview.html).toContain("Deferred until move-in");
  await send("POST", `${itemPath}/mark-ready`, {});
  expect((await (await page.request.get(`/api${itemPath}`)).json()).completionStatus).toBe("YES");
  expect((await page.request.post(`/api${reportPath}/items/${item.id}/resident-pdf`, { headers, data: { version: saved.draft.version } })).status()).toBe(409);
  // Saved inspection dates are never replaced when the editor is reopened.
  await report.getByTestId("final-report-date").fill("2026-09-01");
  await report.getByTestId("final-report-save-draft").click();
  await expect(report.getByTestId("final-report-save-draft")).toBeDisabled();
  await report.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("button", { name: "Inspection details / report", exact: true }).click();
  await expect(report.getByTestId("final-report-date")).toHaveValue("2026-09-01");
  await send("PATCH", itemPath, { applicant: "Incoming Demo Resident" });
  const moveIn = await (await page.request.get(`/api${reportPath}?itemId=${item.id}`)).json();
  expect(moveIn.item.stockInspection).toBe(false);
  const approval = await page.request.post(`/api${itemPath}/mark-ready`, { headers, data: {} });
  expect(approval.status()).toBe(409);
  expect(await approval.text()).toContain("confirm the home/mailbox key");
});
