import { expect, test } from "@playwright/test";

test("simple project input saves product link and total and preserves them in backups", async ({ page }, testInfo) => {
  test.setTimeout(120000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const session = await (await page.request.get("/api/auth/me")).json();
  const headers = { "x-csrf-token": session.csrfToken };
  const response = await page.request.post("/api/operations/properties", { headers, data: { code: `SIMPLE${Date.now()}`, name: "Simple entry fixture" } });
  expect(response.ok()).toBeTruthy();
  const { property } = await response.json();
  await page.reload();
  await page.getByTestId("property-filter").selectOption(property.id);
  await page.getByTestId("module-rail-projects").click();
  await page.getByTestId("projects-quick-capture-open").click();
  await page.getByTestId("projects-quick-capture-title").fill("Dog stations");
  await page.getByTestId("projects-product-url").fill("https://www.amazon.com/dp/EXAMPLE");
  await page.getByTestId("projects-estimated-total").fill("299.95");
  const created = page.waitForResponse(r => r.url().endsWith("/api/projects/records") && r.request().method() === "POST");
  await page.getByTestId("projects-quick-capture-save").click();
  const savedResponse = await created;
  expect(savedResponse.ok(), await savedResponse.text()).toBeTruthy();
  const { record } = await savedResponse.json();
  expect(record.productUrl).toBe("https://www.amazon.com/dp/EXAMPLE");
  expect(record.estimatedCost).toBe(299.95);
  expect(record.actualCost).toBeNull();
  await page.getByRole("button", { name: "View Record", exact: true }).click();
  await expect(page.getByRole("link", { name: "View product / vendor" })).toHaveAttribute("href", record.productUrl);
  await page.getByText("Edit title, link & total", { exact: true }).click();
  const basics = page.locator("form").filter({ has: page.getByRole("button", { name: "Save basics", exact: true }) });
  await basics.getByLabel("Estimated total ($)", { exact: true }).fill("349.50");
  await basics.getByRole("button", { name: "Save basics", exact: true }).click();
  await expect(basics).toContainText("Basics saved.");
  const stored = await (await page.request.get(`/api/projects/records/${record.id}`)).json();
  expect(stored.record.estimatedCost).toBe(349.5);
  const exported = await (await page.request.get("/api/admin/export")).json();
  const copy = exported.data.projectRecords.find((r: any) => r.title === "Dog stations");
  expect(copy.productUrl).toBe(record.productUrl);
  const backup = { ...exported, data: { ...Object.fromEntries(Object.keys(exported.data).map(key => [key, []])), projectRecords: [{ ...copy, title: "Restored dog stations", portableKey: "restored-dog-stations" }] } };
  const restored = await page.request.post("/api/admin/import", { headers, data: { backup, dryRun: false } });
  expect(restored.ok(), await restored.text()).toBeTruthy();
  const list = await (await page.request.get(`/api/projects/records?propertyId=${property.id}`)).json();
  expect(list.records.find((r: any) => r.title === "Restored dog stations").productUrl).toBe(record.productUrl);
  const unsafe = await page.request.patch(`/api/projects/records/${record.id}`, { headers, data: { productUrl: "javascript:alert(1)" } });
  expect(unsafe.status()).toBe(400);
  for (const width of [390, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    await page.screenshot({ path: testInfo.outputPath(`simple-project-${width}.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(2);
  }
});

test("module daily actions stay reachable without expanded setup forms", async ({ page }) => {
  test.setTimeout(120000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  await expect(page.getByTestId("property-filter").locator("option").nth(1)).toBeAttached();
  const propertyId = await page.getByTestId("property-filter").locator("option").evaluateAll(options => options.map(option => (option as HTMLOptionElement).value).find(Boolean)!);
  await page.getByTestId("property-filter").selectOption(propertyId);
  await page.getByTestId("module-rail-property-wiki").click();
  await page.getByLabel("Browse knowledge").selectOption("utilities");
  await expect(page.getByTestId("property-wiki-emergency-mode")).toBeVisible();
  await page.getByLabel("Browse knowledge").selectOption("overview");
  await page.getByTestId("module-rail-pest").click();
  const pest = page.getByTestId("pest-control-panel");
  await expect(pest.getByRole("button", { name: "New request", exact: true })).toBeVisible();
  await expect(pest.locator("#pest-new-request")).toBeHidden();
  await page.getByTestId("module-rail-lease-compliance").click();
  const lease = page.getByTestId("lease-compliance-panel");
  await expect(lease.getByLabel("Issue view", { exact: true })).toHaveValue("active");
  await expect(page.getByTestId("lease-quick-capture-form")).toBeHidden();
  await lease.getByLabel("Issue view", { exact: true }).selectOption("resolved");
  await expect(lease).toContainText("Resolved means the issue was addressed.");
  await page.getByTestId("module-rail-refrigerant").click();
  const refrigerant = page.getByTestId("refrigerant-panel");
  await expect(refrigerant.locator(".refrigerant-quick-grid form").first()).toBeHidden();
  await refrigerant.getByRole("button", { name: "Record charge", exact: true }).click();
  await expect(refrigerant.locator(".refrigerant-quick-grid form").first()).toBeVisible();
  await refrigerant.getByRole("button", { name: "Record recovery", exact: true }).click();
  await expect(refrigerant.locator(".refrigerant-quick-grid form").first()).toBeHidden();
  await expect(refrigerant.locator(".refrigerant-quick-grid form").nth(1)).toBeVisible();
  await page.getByTestId("module-rail-pm").click();
  await expect(page.getByText("Export reports", { exact: true })).toBeVisible();
  await page.getByTestId("module-rail-pool").click();
  const pool = page.getByTestId("pool-log-panel");
  await pool.getByRole("button", { name: "Log readings", exact: true }).first().click();
  await expect(page.getByTestId("pool-daily-form")).toBeVisible();
  await page.getByTestId("module-rail-oncall").click();
  await page.getByRole("button", { name: "Manage on-call", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save on-call", exact: true })).toBeVisible();
  await expect(page.getByText("Schedule settings & sharing", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /View:/ }).click();
  await page.getByTestId("tab-vendors").click();
  await expect(page.getByTestId("vendor-create-form")).toBeHidden();
  await page.getByRole("button", { name: "Add vendor", exact: true }).click();
  await expect(page.getByTestId("vendor-create-name")).toBeVisible();
  await page.getByTestId("vendor-create-name").fill("Unsaved vendor fixture");
  await page.getByRole("button", { name: "Add vendor", exact: true }).click();
  await page.getByRole("button", { name: "Add vendor", exact: true }).click();
  await expect(page.getByTestId("vendor-create-name")).toHaveValue("Unsaved vendor fixture");
  await page.getByRole("button", { name: /View:/ }).click();
  await page.getByTestId("tab-maps").click();
  await expect(page.getByTestId("property-maps-create-name")).toBeHidden();
  await page.getByText("Map setup & exports", { exact: true }).click();
  await expect(page.getByTestId("property-maps-create-name")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(2);
});

test("Spanish simple project fields and compact navigation are available", async ({ page }) => {
  const login = await page.request.post("/api/auth/login", { data: { identifier: process.env.ADMIN_EMAIL || "admin@example.com", password: process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456" } });
  expect(login.ok()).toBeTruthy();
  await page.route("**/api/auth/me", async route => {
    const response = await route.fetch();
    const body = await response.json();
    await route.fulfill({ response, json: { ...body, user: { ...body.user, language: "es" } } });
  });
  await page.goto("/");
  await page.getByTestId("module-rail-projects").click();
  await page.getByTestId("projects-quick-capture-open").click();
  await expect(page.getByText("¿Qué se necesita?", { exact: true })).toBeVisible();
  await expect(page.getByText("Enlace del producto (opcional)", { exact: true })).toBeVisible();
  await expect(page.getByText("Total estimado ($, opcional)", { exact: true })).toBeVisible();
  await page.getByTestId("module-rail-lease-compliance").click();
  await expect(page.getByLabel("Vista de problemas", { exact: true })).toHaveValue("active");
  await page.getByTestId("module-rail-property-wiki").click();
  await expect(page.getByLabel("Explorar conocimiento")).toBeVisible();
});
