import { expect, test } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";

test("pool reports include complete chemistry and readable paginated details", async ({ page }, testInfo) => {
  test.setTimeout(120000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await page.getByTestId("login-submit").click();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const propertyId = await page.getByTestId("property-filter").locator("option").nth(1).getAttribute("value");
  const headers = { "x-csrf-token": (await (await page.request.get("/api/auth/me")).json()).csrfToken };
  const created = await page.request.post("/api/pool/facilities", { headers, data: { propertyId, name: "Full chemistry <test>", type: "POOL" } });
  expect(created.status()).toBe(201);
  const facilityId = (await created.json()).facility.id;
  const entry = await page.request.post("/api/pool/entries", { headers, data: { propertyId, facilityId, logDate: "2026-08-02", logTime: "09:15", ph: 7.4, freeChlorine: 3.5, combinedChlorine: 0, totalChlorine: 3.5, totalAlkalinity: 90, cyanuricAcid: 42, calciumHardness: 275, waterTemperature: 81, pumpRunning: true, vacuumed: true, notes: "Operator note <script>bad()</script>", chemicalAdditions: [{ chemicalName: "Granular product", amount: 20, unit: "OUNCES", notes: "Product addition note" }], safetyChecks: [{ label: "Gate/self-closing latch checked", value: "FAIL", notes: "Latch needs adjustment" }] } });
  expect(entry.status(), await entry.text()).toBe(201);
  const entryId = (await entry.json()).entry.id;
  const file = await page.request.post(`/api/pool/entries/${entryId}/attachments`, { headers, multipart: { file: { name: "test-result.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\nPool record fixture\n%%EOF") } } });
  expect(file.status()).toBe(201);
  const query = `?propertyId=${propertyId}&from=2026-08-02&to=2026-08-02`;
  await page.goto(`/api/pool/report.html${query}`);
  await expect(page.getByText("Full chemistry <test>", { exact: false }).first()).toBeVisible();
  const labels = ["Free chlorine", "Combined chlorine", "Total chlorine", "Total alkalinity", "Cyanuric acid (stabilizer)", "Calcium hardness", "Water temperature"];
  for (const label of labels) await expect(page.locator(".reading").filter({ hasText: label }).first()).toBeVisible();
  await expect(page.locator(".reading").filter({ hasText: "Combined chlorine" }).first()).toContainText("0 ppm");
  await expect(page.getByText("Operator note <script>bad()</script>")).toBeVisible();
  await expect(page.getByText("Latch needs adjustment")).toBeVisible();
  await page.emulateMedia({ media: "print" });
  await page.setViewportSize({ width: 739, height: 974 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("pool-report-print-layout.png"), fullPage: true });
  const report = await page.request.get(`/api/pool/report.pdf${query}`);
  expect(report.status()).toBe(200); expect(report.headers()["content-type"]).toBe("application/pdf");
  const pdfPath = testInfo.outputPath("full-chemistry.pdf");
  await writeFile(pdfPath, await report.body());
  const text = execFileSync("pdftotext", ["-layout", pdfPath, "-"], { encoding: "utf8" });
  for (const label of labels) expect(text).toContain(label);
  for (const value of ["90", "42", "275", "81", "Latch needs adjustment", "Operator note", "Page 1 of", "1 lb 4 oz", "Product addition note", "test-result.pdf"]) expect(text).toContain(value);
  const csv = await (await page.request.get(`/api/pool/export.csv${query}`)).text();
  for (const value of ["calcium_hardness", "safety_checks", "vacuumed", "275", "Latch needs adjustment"]) expect(csv).toContain(value);
  const partial = await page.request.post("/api/pool/entries", { headers, data: { propertyId, facilityId, logDate: "2026-08-03", notes: "Long note. ".repeat(900) + "END OF LONG NOTE" } });
  expect(partial.status()).toBe(201);
  const longPdf = await page.request.get(`/api/pool/report.pdf?propertyId=${propertyId}&from=2026-08-03&to=2026-08-03`);
  expect(longPdf.status()).toBe(200);
  const longPath = testInfo.outputPath("long-notes.pdf");
  await writeFile(longPath, await longPdf.body());
  const longText = execFileSync("pdftotext", [longPath, "-"], { encoding: "utf8" });
  expect(longText).toContain("Not recorded"); expect(longText).toContain("END OF LONG NOTE");
  const empty = await (await page.request.get(`/api/pool/report.html?propertyId=${propertyId}&from=1990-01-01&to=1990-01-01`)).text();
  expect(empty).toContain("No pool logs found");
});
