import { expect, test, type Page } from "@playwright/test";

test("compact light defaults and split final walk correction loop", async ({ page, browser }, testInfo) => {
  test.setTimeout(120000);
  await page.goto("/");
  const origin = new URL(page.url()).origin;
  const login = async (target: Page, username: string, password: string) => {
    target.setDefaultTimeout(15000);
    await target.goto(origin);
    await target.getByTestId("login-email").fill(username);
    await target.getByTestId("login-password").fill(password);
    await target.getByTestId("login-submit").click();
    await expect(target.getByTestId("property-filter")).toBeVisible();
    return { "x-csrf-token": (await (await target.request.get(`${origin}/api/auth/me`)).json()).csrfToken };
  };
  const admin = await login(page, process.env.ADMIN_EMAIL || "admin@example.com", process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await expect(page.locator(".app-shell")).toHaveAttribute("data-theme", "light");
  await expect(page.locator(".app-shell")).toHaveClass(/compact-mode/);
  const send = async (target: Page, headers: Record<string, string>, method: string, path: string, data?: unknown) => {
    const response = await target.request.fetch(`${origin}/api${path}`, { method, headers, data });
    expect(response.ok(), await response.text()).toBe(true);
    return response.json();
  };
  const stamp = Date.now();
  const password = "Test-Only-Turn!12345";
  const { property } = await send(page, admin, "POST", "/operations/properties", { code: `SPLIT${stamp}`, name: "Split walk property" });
  const staff = [];
  for (const role of ["TECH", "LEASING"]) staff.push((await send(page, admin, "POST", "/admin/users", { username: `${role.toLowerCase()}${stamp}`, fullName: `${role} ${stamp}`, role, propertyIds: [property.id], password })).user);
  const { unit } = await send(page, admin, "POST", "/operations/units", { propertyId: property.id, number: "SPLIT-1" });
  const meta = await (await page.request.get(`${origin}/api/meta`)).json();
  const group = meta.boardSections.find((s: any) => s.propertyId === property.id && s.sectionType === "MAKE_READY").key;
  const item = await send(page, admin, "POST", "/make-ready-items", { propertyId: property.id, unitId: unit.id, unitNumber: unit.number, itemName: unit.number, boardGroup: group, vacancyStatus: "VACANT NOT LEASED NOT READY" });
  const itemPath = `/make-ready-items/${item.id}`;
  const reportPath = `/final-walk-reports/${property.id}`;
  await send(page, admin, "PATCH", itemPath, { assignedTech: staff[0].fullName });
  await send(page, admin, "PUT", `/automations/final-walk/${property.id}`, { enabled: true, inspectors: [staff[1].id] });
  const techContext = await browser.newContext();
  const leasingContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const tech = await techContext.newPage();
    const techHeaders = await login(tech, staff[0].username, password);
    await expect(tech.getByTestId(`my-work-item-${item.id}`)).toBeVisible();
    await expect(tech.getByTestId(`my-work-move-in-${item.id}`)).toHaveCount(0);
    const moveIn = new Date();
    moveIn.setUTCDate(moveIn.getUTCDate() + 3);
    const moveInDate = moveIn.toISOString().slice(0, 10);
    await send(page, admin, "PATCH", itemPath, { moveInDate });
    await tech.reload();
    const moveInCue = tech.getByTestId(`my-work-move-in-${item.id}`);
    await expect(moveInCue.getByText("Move-in", { exact: true })).toBeVisible();
    await expect(moveInCue).toContainText("3 days till move-in");
    await expect(moveInCue.locator("time")).toHaveAttribute("datetime", moveInDate);
    await tech.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Open work item", exact: true }).click();
    const prep = tech.getByTestId("resident-codes-panel");
    const showCodes = prep.getByRole("button", { name: "Show codes", exact: true });
    await showCodes.click();
    await expect(prep.getByLabel("New resident door code", { exact: true })).toHaveAttribute("type", "text");
    expect(await showCodes.count()).toBe(0);
    await prep.getByRole("button", { name: "Hide codes", exact: true }).click();
    expect(await prep.getByRole("button", { name: "Show codes", exact: true }).evaluate(button => Boolean(button.compareDocumentPosition(document.querySelector('[autocomplete="new-password"]')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true);
    await expect(prep.locator('[data-testid^="tech-check-"]')).toHaveCount(8);
    for (const input of await prep.locator('[data-testid^="tech-check-"]').all()) await input.selectOption("CHECKED");
    await prep.getByLabel("Home keys made", { exact: true }).fill("2");
    await prep.getByLabel("Mailbox key count", { exact: true }).fill("2");
    await prep.getByLabel("Access fobs prepared", { exact: true }).fill("1");
    await prep.getByLabel("Garage remotes prepared", { exact: true }).fill("0");
    await prep.getByRole("button", { name: "Save preparation & resident details", exact: true }).click();
    await expect(prep.getByRole("status")).not.toContainText("Unsaved");
    await expect.poll(async () => (await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json()).value.homeKeys).toBe("2");
    await send(tech, techHeaders, "PATCH", itemPath, { makeReadyStatus: "DONE" });
    await tech.reload();
    await expect(tech.getByTestId(`my-work-item-${item.id}`).getByText("Repairs done", { exact: true }).first()).toBeVisible();
    await expect(tech.getByTestId(`my-work-final-walk-pending-${item.id}`)).toHaveCount(0);
    await send(page, admin, "PATCH", itemPath, { paintStatus: "DONE", cleaningStatus: "DONE" });
    await tech.reload();
    const techCard = tech.getByTestId(`my-work-item-${item.id}`);
    await expect(techCard.getByText("Pending final walk", { exact: true })).toBeVisible();
    await expect(techCard.getByTestId(`my-work-final-walk-pending-${item.id}`)).toContainText("Your repair work is complete");
    await expect(techCard.getByRole("button", { name: "Start Work", exact: true })).toHaveCount(0);
    await expect(techCard.getByLabel(`Repair status ${unit.number}`)).toHaveValue("DONE");
    await tech.getByTestId("drawer-pane-work").click();
    const reopenedPrep = tech.getByTestId("resident-codes-panel");
    const firstCheck = reopenedPrep.locator('[data-testid^="tech-check-"]').first();
    await expect(firstCheck).toBeEnabled();
    await expect(reopenedPrep.getByLabel("New resident door code", { exact: true })).toBeDisabled();
    await firstCheck.selectOption("NOT_CHECKED");
    await reopenedPrep.getByRole("button", { name: "Save preparation checks", exact: true }).click();
    await expect(reopenedPrep.getByRole("status")).toContainText("Preparation and resident details saved");
    await firstCheck.selectOption("CHECKED");
    await reopenedPrep.getByRole("button", { name: "Save preparation checks", exact: true }).click();
    await expect(reopenedPrep.getByRole("status")).toContainText("Preparation and resident details saved");
    const inspector = await leasingContext.newPage();
    const inspectorHeaders = await login(inspector, staff[1].username, password);
    await inspector.getByRole("button", { name: /View:/ }).click();
    await inspector.getByTestId("tab-my-work").click();
    await expect(inspector.getByTestId(`my-work-item-${item.id}`).getByText("Pending final walk", { exact: true })).toBeVisible();
    await expect(inspector.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Start Work", exact: true })).toBeVisible();
    await inspector.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Inspect or hand off", exact: true }).click();
    await inspector.getByRole("button", { name: "Inspection details / report", exact: true }).click();
    const report = inspector.getByTestId("final-report-editor");
    await expect(report.locator('[data-testid^="final-report-result-"]')).toHaveCount(9);
    await expect(report.getByLabel("Home key count", { exact: true })).toHaveValue("2");
    await expect(report.getByLabel("Access fob count", { exact: true })).toHaveValue("1");
    await expect(report.getByRole("combobox", { name: /condensate/ })).toHaveCount(0);
    await report.getByTestId("final-report-date").fill("2026-09-15");
    await report.getByTestId("final-report-result-presentation-v2-3").selectOption("ATTENTION");
    await expect(report.locator('.final-report-check[data-check-status="ATTENTION"]')).toHaveCount(1);
    await report.getByTestId("final-report-note-presentation-v2-3").fill("Touch up entry trim");
    await report.getByLabel("Internal follow-up for technician", { exact: true }).fill("Internal correction request");
    await report.getByRole("button", { name: "Save and send corrections to technician", exact: true }).click();
    await expect(report).toBeHidden();
    const returned = await (await tech.request.get(`${origin}/api${itemPath}`)).json();
    expect(returned).toMatchObject({ makeReadyStatus: "IN PROGRESS", paintStatus: "DONE", cleaningStatus: "DONE", completionStatus: "NO" });
    await tech.reload();
    await expect(tech.getByTestId(`my-work-final-walk-pending-${item.id}`)).toHaveCount(0);
    await expect(tech.getByTestId(`my-work-item-${item.id}`)).toHaveClass(/work-correction-card/);
    await expect(tech.getByTestId(`my-work-item-${item.id}`).locator('.work-correction-badge')).toHaveText("Final-walk corrections");
    await expect(tech.getByTestId(`my-work-item-${item.id}`)).not.toContainText("FINAL_WALK_CORRECTION");
    await expect(tech.getByTestId(`my-work-status-${item.id}`)).toHaveValue("IN PROGRESS");
    await tech.getByTestId("item-drawer-close").click();
    await expect(tech.getByTestId("item-drawer")).toBeHidden();
    for (const theme of ["light", "dark"]) {
      await tech.setViewportSize({ width: 390, height: 844 });
      await tech.evaluate(theme => document.documentElement.dataset.theme = theme, theme);
      await tech.getByTestId(`my-work-item-${item.id}`).screenshot({ path: testInfo.outputPath(`correction-${theme}.png`) });
      expect(await tech.getByTestId(`my-work-item-${item.id}`).evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
    }
    const assigned = await (await tech.request.get(`${origin}/api/assigned-work`)).json();
    expect(assigned.entries.some((entry: any) => entry.sourceId === item.id && entry.workCategory === "FINAL_WALK_CORRECTION")).toBe(true);
    await expect(tech.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Start Work", exact: true })).toBeVisible();
    expect(JSON.stringify(await (await tech.request.get(`${origin}/api/notifications`)).json())).toContain("Final walk returned for corrections");
    const work = await (await tech.request.get(`${origin}/api/my-work`)).json();
    expect(work.items.some((row: any) => row.id === item.id)).toBe(true);
    let codes = await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json();
    expect(codes.readOnly).toBe(false);
    expect(codes.technicianFollowUp).toContain("Touch up entry trim");
    expect(codes.correctionPending).toBe(true);
    await tech.getByRole("button", { name: "Open corrections", exact: true }).click();
    await expect(tech.getByTestId("drawer-correction-next-step")).toBeVisible();
    await tech.getByRole("button", { name: "Review corrections", exact: true }).click();
    await expect(prep.getByLabel("Technician resolution", { exact: true })).toBeFocused();
    await expect(prep.locator('.work-correction-panel')).toContainText("Touch up entry trim");
    await prep.getByLabel("Technician resolution", { exact: true }).fill("Entry trim touched up and dry");
    await prep.getByRole("button", { name: "Save preparation & resident details", exact: true }).click();
    await expect(prep.locator('.work-correction-panel')).toHaveCount(0);
    await expect(tech.getByTestId("drawer-correction-next-step")).toHaveCount(0);
    await expect(tech.getByTestId(`my-work-item-${item.id}`)).not.toHaveClass(/work-correction-card/);
    codes = await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json();
    expect(codes.correctionPending).toBe(false);
    await tech.reload();
    await expect(tech.getByTestId(`my-work-item-${item.id}`)).not.toHaveClass(/work-correction-card/);
    await send(tech, techHeaders, "PATCH", itemPath, { makeReadyStatus: "DONE" });
    const assignment = await (await page.request.get(`${origin}/api${itemPath}/final-walk`)).json();
    expect(assignment.block.assignedUserId).toBe(staff[1].id);
    let data = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(data.draft.value.technicianResolution).toBe("Entry trim touched up and dry");
    for (const check of data.checks) data.draft.value.results[check.id] = { status: "CHECKED", note: "" };
    data.draft.value.handoffConfirmed = true;
    data.draft.value.gateCode = "RESIDENT-GATE";
    data.draft.value.pedestrianCode = "RESIDENT-WALK";
    data.draft.value.includeResidentCodes = true;
    // The inspector cannot overwrite preparation evidence supplied by the tech.
    data.draft.value.technicianResults = {};
    await send(inspector, inspectorHeaders, "PUT", `${reportPath}/items/${item.id}`, { version: data.draft.version, value: data.draft.value });
    data = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(Object.keys(data.draft.value.technicianResults)).toHaveLength(8);
    const preview = await send(inspector, inspectorHeaders, "POST", `${reportPath}/preview`, { itemId: item.id, settings: data.settings.value, draft: data.draft.value, format: "html" });
    expect(preview.html).toContain("RESIDENT-GATE");
    expect(preview.html).not.toContain("Internal correction request");
    expect(preview.html).not.toContain("Entry trim touched up and dry");
    const pdf = await send(inspector, inspectorHeaders, "POST", `${reportPath}/preview`, { itemId: item.id, settings: data.settings.value, draft: data.draft.value, format: "pdf" });
    expect((Buffer.from(pdf.pdfBase64, "base64").toString("latin1").match(/\/Type\s*\/Page\b/g) ?? []).length).toBe(1);
    // Celebrations can be muted independently without changing final-walk alerts.
    await send(inspector, inspectorHeaders, "PATCH", "/notifications/preferences/POND_MILESTONE", { enabled: false });
    expect((await (await tech.request.get(`${origin}/api/pond/milestones?propertyId=${property.id}`)).json()).properties[0].completedTurns).toBe(0);
    expect((await tech.request.get(`${origin}/api/pond/milestones?propertyId=outside-scope`)).status()).toBe(403);
    await send(inspector, inspectorHeaders, "POST", `${itemPath}/mark-ready`, {});
    const milestones = await (await tech.request.get(`${origin}/api/pond/milestones`)).json();
    expect(milestones.properties).toHaveLength(1);
    expect(milestones.properties[0]).toMatchObject({ id: property.id, completedTurns: 1 });
    const teamNotes = (await (await tech.request.get(`${origin}/api/notifications`)).json()).notifications.filter((note: any) => note.category === "POND_MILESTONE");
    expect(teamNotes).toHaveLength(1);
    expect(teamNotes[0]).toMatchObject({ pushPending: false, item: null, property: { id: property.id } });
    expect((await (await inspector.request.get(`${origin}/api/notifications`)).json()).notifications.filter((note: any) => note.category === "POND_MILESTONE")).toHaveLength(0);
    await send(tech, techHeaders, "POST", `/notifications/${teamNotes[0].id}/read`, {});
    expect((await (await page.request.get(`${origin}/api${itemPath}`)).json()).completionStatus).toBe("YES");
    data = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(data.canEditDraft).toBe(true);
    expect(data.item.unitReady).toBe(true);
    const completed = await send(inspector, inspectorHeaders, "PUT", `${reportPath}/items/${item.id}`, { version: data.draft.version, value: { ...data.draft.value, parking: "Space 12" } });
    expect((await (await page.request.get(`${origin}/api${itemPath}`)).json()).completionStatus).toBe("YES");
    const resident = await send(inspector, inspectorHeaders, "POST", `${reportPath}/items/${item.id}/resident-pdf`, { version: completed.version });
    expect((Buffer.from(resident.pdfBase64, "base64").toString("latin1").match(/\/Type\s*\/Page\b/g) ?? []).length).toBe(1);
    expect((await inspector.request.post(`${origin}/api${reportPath}/items/${item.id}/resident-pdf`, { headers: inspectorHeaders, data: { version: completed.version - 1 } })).status()).toBe(409);
    expect((await tech.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).status()).toBe(403);
    const readyPrep = await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json();
    expect(readyPrep.preparationReadOnly).toBe(false);
    expect(readyPrep.readOnly).toBe(true);
    const checkId = Object.keys(readyPrep.value.technicianResults)[0];
    const revised = await send(tech, techHeaders, "PUT", `${itemPath}/resident-codes`, { version: readyPrep.version, value: { technicianResults: { ...readyPrep.value.technicianResults, [checkId]: { status: "NOT_CHECKED", note: "" } } } });
    const revisedReport = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(revisedReport.draft.value.handoffConfirmed).toBe(false);
    expect((await (await page.request.get(`${origin}/api${itemPath}`)).json()).completionStatus).toBe("YES");
    expect((await inspector.request.post(`${origin}/api${reportPath}/items/${item.id}/resident-pdf`, { headers: inspectorHeaders, data: { version: revised.version } })).status()).toBe(409);
    expect((await tech.request.put(`${origin}/api${itemPath}/resident-codes`, { headers: techHeaders, data: { version: revised.version, value: { residentDoorCode: "BLOCKED" } } })).status()).toBe(409);
    await send(tech, techHeaders, "PUT", `${itemPath}/resident-codes`, { version: revised.version, value: { technicianResults: readyPrep.value.technicianResults } });
    const recheck = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    await send(inspector, inspectorHeaders, "PUT", `${reportPath}/items/${item.id}`, { version: recheck.draft.version, value: { ...recheck.draft.value, handoffConfirmed: true } });
    // Ready units imported without an inspection assignment remain editable by leasing,
    // but cannot produce a resident copy without recorded checks.
    const imported = await send(page, admin, "POST", "/make-ready-items", { propertyId: property.id, unitNumber: "READY-2", itemName: "READY-2", boardGroup: group, vacancyStatus: "VACANT LEASED READY" });
    const importedData = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${imported.id}`)).json();
    expect(importedData.canEditDraft).toBe(true);
    expect((await (await inspector.request.get(`${origin}/api/make-ready-items/${imported.id}/final-walk`)).json()).reportAvailable).toBe(true);
    const incomplete = await send(inspector, inspectorHeaders, "PUT", `${reportPath}/items/${imported.id}`, { version: importedData.draft.version, value: importedData.draft.value });
    expect((await inspector.request.post(`${origin}/api${reportPath}/items/${imported.id}/resident-pdf`, { headers: inspectorHeaders, data: { version: incomplete.version } })).status()).toBe(409);
    await inspector.getByRole("button", { name: "Inspection details / report", exact: true }).click();
    await expect(report.getByText("Completed unit / inspection report", { exact: true })).toBeVisible();
    await expect(report.getByLabel("Parking / garage assignment", { exact: true })).toHaveValue("Space 12");
    const download = inspector.waitForEvent("download");
    await report.getByTestId("final-report-resident-pdf").click();
    expect((await download).suggestedFilename()).toContain("SPLIT-1");
    await report.getByRole("button", { name: "Close dialog" }).click();
    await inspector.getByTestId("item-drawer-close").click();
    await inspector.getByRole("button", { name: /View:/ }).click();
    await inspector.getByTestId("tab-table").click();
    await inspector.getByTestId("mobile-details-split-1").click();
    for (const width of [320, 390, 1280]) {
      await inspector.setViewportSize({ width, height: 844 });
      const drawer = inspector.getByTestId("item-drawer");
      const badges = await drawer.locator(".drawer-pills").boundingBox();
      const action = await inspector.getByTestId("completed-unit-report").boundingBox();
      const close = await inspector.getByTestId("item-drawer-close").boundingBox();
      expect(badges).not.toBeNull(); expect(action).not.toBeNull(); expect(close).not.toBeNull();
      expect(action!.y - (badges!.y + badges!.height)).toBeGreaterThanOrEqual(8);
      expect(action!.x + action!.width).toBeLessThanOrEqual(close!.x);
      expect(await drawer.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
    }
    await inspector.setViewportSize({ width: 390, height: 844 });
    await inspector.screenshot({ path: testInfo.outputPath("completed-unit-header-mobile.png") });
    await inspector.getByTestId("completed-unit-report").click();
    await expect(report.getByTestId("final-report-resident-pdf")).toBeVisible();
    await inspector.screenshot({ path: testInfo.outputPath("final-walk-mobile.png") });
    // Restore the vacant fixture after move-in automation for the separate reopen checks.
    await send(page, admin, "PATCH", itemPath, { moveInDate: null, vacancyStatus: "VACANT NOT LEASED NOT READY" });
    // Reopening is an audited management action, not another technician status edit.
    for (const [target, headers] of [[tech, techHeaders], [inspector, inspectorHeaders]] as const) {
      expect((await target.request.post(`${origin}/api${itemPath}/reopen-final-walk`, { headers, data: { reason: "Final walk still required" } })).status()).toBe(403);
    }
    expect((await page.request.post(`${origin}/api${itemPath}/reopen-final-walk`, { headers: admin, data: { reason: "short" } })).status()).toBe(400);
    expect((await page.request.post(`${origin}/api/make-ready-items/${imported.id}/reopen-final-walk`, { headers: admin, data: { reason: "Trades not yet completed" } })).status()).toBe(409);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.reload();
    await page.getByTestId("property-filter").selectOption(property.id);
    await page.getByRole("button", { name: /View:/ }).click();
    await page.getByTestId("tab-table").click();
    await page.getByTestId("mobile-details-split-1").click();
    const reopen = page.getByTestId("reopen-final-walk");
    await reopen.locator("summary").click();
    await expect(reopen.getByRole("button")).toBeDisabled();
    await reopen.getByLabel("Reason for reopening").fill("Completion recorded before independent final walk");
    await reopen.getByRole("button", { name: "Reopen and request final walk", exact: true }).click();
    await expect(page.getByText("Reopened for final walk. The inspector has been assigned and notified.", { exact: true })).toBeVisible();
    await expect(reopen).toBeHidden();
    const reopened = await (await page.request.get(`${origin}/api${itemPath}`)).json();
    expect(reopened).toMatchObject({ completionStatus: "NO", makeReadyStatus: "DONE", paintStatus: "DONE", cleaningStatus: "DONE", boardGroup: group, vacancyStatus: "VACANT NOT LEASED NOT READY" });
    const reassigned = await (await inspector.request.get(`${origin}/api${itemPath}/final-walk`)).json();
    expect(reassigned.block.assignedUserId).toBe(staff[1].id);
    expect(reassigned.block.id).not.toBe(assignment.block.id);
    expect((await (await inspector.request.get(`${origin}/api/my-work`)).json()).items.some((row: any) => row.id === item.id)).toBe(true);
    expect((await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json()).draft.value.parking).toBe("Space 12");
    expect((await page.request.post(`${origin}/api${itemPath}/reopen-final-walk`, { headers: admin, data: { reason: "Duplicate reopen should fail" } })).status()).toBe(409);
    // A reopened turn can be approved again, but credit and read notices stay unchanged.
    await send(inspector, inspectorHeaders, "POST", `${itemPath}/mark-ready`, {});
    await send(page, admin, "POST", `${itemPath}/mark-ready`, {});
    expect((await (await page.request.get(`${origin}/api/pond/milestones?propertyId=${property.id}`)).json()).properties[0].completedTurns).toBe(1);
    const repeatedNotes = (await (await tech.request.get(`${origin}/api/notifications`)).json()).notifications.filter((note: any) => note.category === "POND_MILESTONE");
    expect(repeatedNotes).toHaveLength(1);
    expect(repeatedNotes[0]).toMatchObject({ id: teamNotes[0].id, isRead: true });
    await send(page, admin, "POST", `/make-ready-items/${imported.id}/mark-ready`, { overrideReason: "Test administrative correction without an inspection" });
    const overridden = await send(page, admin, "POST", "/make-ready-items", { propertyId: property.id, unitNumber: "OVERRIDE-3", itemName: "OVERRIDE-3", boardGroup: group, vacancyStatus: "VACANT NOT LEASED NOT READY" });
    await send(page, admin, "POST", `/make-ready-items/${overridden.id}/mark-ready`, { overrideReason: "Test pending turn override without verified completion" });
    expect((await (await page.request.get(`${origin}/api/pond/milestones?propertyId=${property.id}`)).json()).properties[0].completedTurns).toBe(1);
    await page.getByTestId("item-drawer-close").click();
    await page.reload();
    await page.getByTestId("notifications-button").click();
    await page.getByTestId("notification-drawer").getByRole("button", { name: /View in Pond/ }).click();
    const teamProgress = page.getByTestId(`pond-team-${property.id}`);
    await expect(teamProgress).toContainText("1 approved turn");
    await expect(teamProgress).toContainText("First team finish");
    await expect(page.getByTestId("notification-drawer")).toHaveCount(0);
    for (const width of [390, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      await teamProgress.scrollIntoViewIfNeeded();
      expect(await teamProgress.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
      await page.screenshot({ path: testInfo.outputPath(`pond-team-${width}.png`) });
    }
    await page.evaluate(() => { localStorage.setItem("makereadyos.themeMode", "dark"); localStorage.setItem("makereadyos.compactMode", "false"); });
    await page.reload();
    await expect(page.locator(".app-shell")).toHaveAttribute("data-theme", "dark");
    await expect(page.locator(".app-shell")).not.toHaveClass(/compact-mode/);
  } finally { await techContext.close(); await leasingContext.close(); }
});
