import { expect, test } from "@playwright/test";

test("Assigned Work drawer loads the unit's past and future work and handles refresh denial", async ({ page }) => {
  test.setTimeout(90000);
  await page.goto("/");
  await page.getByTestId("login-email").fill(process.env.ADMIN_EMAIL || "admin@example.com");
  await page.getByTestId("login-password").fill(process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  const login = page.waitForResponse(response => response.url().endsWith("/api/auth/login") && response.request().method() === "POST");
  await page.getByTestId("login-submit").click();
  const { csrfToken, user } = await (await login).json();
  await expect(page.getByTestId("property-filter")).toBeVisible();
  const post = async (path: string, data: unknown) => {
    const response = await page.request.post(`/api${path}`, { headers: { "x-csrf-token": csrfToken }, data });
    expect(response.ok(), await response.text()).toBeTruthy();
    return response.json();
  };
  const { property } = await post("/operations/properties", { code: `WP${Date.now()}`, name: "Work Plan Test" });
  const { unit } = await post("/operations/units", { propertyId: property.id, number: "PLAN-ONLY" });
  const meta = await (await page.request.get("/api/meta")).json();
  const section = meta.boardSections.find((entry: { propertyId: string; sectionType: string }) => entry.propertyId === property.id && entry.sectionType === "MAKE_READY");
  const item = await post("/make-ready-items", { propertyId: property.id, unitId: unit.id, boardGroup: section.key, itemName: unit.number, unitNumber: unit.number, assignedTech: user.fullName, vacancyStatus: "VACANT NOT LEASED NOT READY", completionStatus: "NO" });
  for (const [category, plannedDate] of [["Past repair visit", "2020-01-06"], ["Make Ready", "2030-01-07"]]) {
    await post("/planning/blocks", { itemId: item.id, assignedUserId: user.id, category, plannedDate, estimatedHours: 1 });
  }
  const { vendor } = await post("/vendors", { name: "Unit-specific painters", trade: "Painting", propertyIds: [property.id] });
  await post("/vendor-assignments", { itemId: item.id, vendorId: vendor.id, trade: "Painting", scheduledDate: "2030-01-08", status: "SCHEDULED" });
  const plan = await (await page.request.get(`/api/planning/items/${item.id}`)).json();
  expect(plan.blocks).toHaveLength(2);
  expect(plan.assignments).toHaveLength(1);
  await page.reload();
  await page.getByRole("button", { name: "View: Table", exact: true }).click();
  await page.getByTestId("tab-assigned-work").click();
  const card = page.getByTestId("assigned-work-panel").locator(".my-work-card").filter({ hasText: "PLAN-ONLY" }).first();
  await card.getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByTestId("assigned-work-panel")).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByTestId("drawer-next-action")).toContainText("Finish repairs");
  await expect(page.getByTestId("drawer-next-action")).toContainText("2030-01-07");
  await expect(page.getByTestId("drawer-next-action")).not.toContainText("Unit-specific painters");
  await page.getByTestId("drawer-pane-all").click();
  const planning = page.getByTestId("drawer-planning-summary");
  const vendors = page.getByTestId("drawer-vendor-assignments");
  await expect(planning).toContainText("2020-01-06");
  await expect(planning).toContainText("2030-01-07");
  await expect(vendors.locator(".attachment-list")).toContainText("Unit-specific painters");
  let status = 503;
  await page.route(`**/api/planning/items/${item.id}`, route => route.fulfill({ status, json: { message: "Injected refresh failure" } }));
  await page.evaluate(() => { window.dispatchEvent(new Event("offline")); window.dispatchEvent(new Event("online")); });
  await expect(planning.getByRole("alert")).toContainText("Could not refresh");
  await expect(planning).toContainText("Past repair visit");
  await expect(vendors).toContainText("Not verified");
  status = 403;
  await planning.getByRole("button", { name: "Retry work plan" }).click();
  await expect(planning).not.toContainText("Past repair visit");
  await expect(vendors.locator(".attachment-list")).toHaveCount(0);
  await page.getByTestId("item-drawer-close").click();
  await expect(page.getByTestId("assigned-work-panel")).toBeVisible();
  await page.unroute(`**/api/planning/items/${item.id}`);
  const filtered = page.waitForResponse(response => response.url().includes("/api/make-ready-items?") && new URL(response.url()).searchParams.get("q") === "NO-MATCH-WORK-PLAN" && response.request().method() === "GET");
  await page.getByRole("textbox", { name: "Search board items" }).fill("NO-MATCH-WORK-PLAN");
  const filteredBody = await (await filtered).json();
  expect(Array.isArray(filteredBody) ? filteredBody : filteredBody.items).toHaveLength(0);
  await card.getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByTestId("item-drawer")).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Search board items" })).toHaveValue("NO-MATCH-WORK-PLAN");
  const draft = page.getByTestId("resident-codes-panel").getByLabel("New resident door code", { exact: true });
  await draft.fill("FICTIONAL-NOT-SAVED");
  let itemStatus = 503;
  await page.route(`**/api/make-ready-items/${item.id}`, route => route.fulfill({ status: itemStatus, json: { message: "Injected unit refresh failure" } }));
  await page.evaluate(() => { window.dispatchEvent(new Event("offline")); window.dispatchEvent(new Event("online")); });
  await expect(page.getByTestId("item-drawer")).toContainText("Could not refresh the unit");
  await expect(draft).toHaveValue("FICTIONAL-NOT-SAVED");
  itemStatus = 403;
  await page.getByTestId("item-drawer").getByRole("button", { name: "Retry unit", exact: true }).click();
  await expect(page.getByTestId("item-drawer")).toHaveCount(0);
  await expect(page.getByTestId("item-load-dialog")).toContainText("Unit unavailable");
});
