import { expect, test, type Page } from "@playwright/test";

test("compact light defaults and split final walk correction loop", async ({ page, browser }, testInfo) => {
  test.setTimeout(120000);
  await page.goto("/");
  const origin = new URL(page.url()).origin;
  const login = async (target: Page, username: string, password: string) => {
    target.setDefaultTimeout(15000);
    await target.goto(origin);
    await target.getByTestId("login-email").fill(username);
    await target.getByTestId("login-password").fill(password);
    await target.getByTestId("login-submit").click();
    await expect(target.getByTestId("property-filter")).toBeVisible();
    return { "x-csrf-token": (await (await target.request.get(`${origin}/api/auth/me`)).json()).csrfToken };
  };
  const admin = await login(page, process.env.ADMIN_EMAIL || "admin@example.com", process.env.ADMIN_PASSWORD || "ChangeThisAdmin!23456");
  await expect(page.locator(".app-shell")).toHaveAttribute("data-theme", "light");
  await expect(page.locator(".app-shell")).toHaveClass(/compact-mode/);
  const send = async (target: Page, headers: Record<string, string>, method: string, path: string, data?: unknown) => {
    const response = await target.request.fetch(`${origin}/api${path}`, { method, headers, data });
    expect(response.ok(), await response.text()).toBe(true);
    return response.json();
  };
  const stamp = Date.now();
  const password = "Test-Only-Turn!12345";
  const { property } = await send(page, admin, "POST", "/operations/properties", { code: `SPLIT${stamp}`, name: "Split walk property" });
  const staff = [];
  for (const role of ["TECH", "LEASING"]) staff.push((await send(page, admin, "POST", "/admin/users", { username: `${role.toLowerCase()}${stamp}`, fullName: `${role} ${stamp}`, role, propertyIds: [property.id], password })).user);
  const { unit } = await send(page, admin, "POST", "/operations/units", { propertyId: property.id, number: "SPLIT-1" });
  const meta = await (await page.request.get(`${origin}/api/meta`)).json();
  const group = meta.boardSections.find((s: any) => s.propertyId === property.id && s.sectionType === "MAKE_READY").key;
  const item = await send(page, admin, "POST", "/make-ready-items", { propertyId: property.id, unitId: unit.id, unitNumber: unit.number, itemName: unit.number, boardGroup: group, vacancyStatus: "VACANT NOT LEASED NOT READY" });
  const itemPath = `/make-ready-items/${item.id}`;
  const reportPath = `/final-walk-reports/${property.id}`;
  await send(page, admin, "PATCH", itemPath, { assignedTech: staff[0].fullName });
  await send(page, admin, "PUT", `/automations/final-walk/${property.id}`, { enabled: true, inspectors: [staff[1].id] });
  const techContext = await browser.newContext();
  const leasingContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const tech = await techContext.newPage();
    const techHeaders = await login(tech, staff[0].username, password);
    await tech.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Open work item", exact: true }).click();
    const prep = tech.getByTestId("resident-codes-panel");
    await expect(prep.locator('[data-testid^="tech-check-"]')).toHaveCount(8);
    for (const input of await prep.locator('[data-testid^="tech-check-"]').all()) await input.selectOption("CHECKED");
    await prep.getByLabel("Home keys made", { exact: true }).fill("2");
    await prep.getByLabel("Mailbox key count", { exact: true }).fill("2");
    await prep.getByLabel("Access fobs prepared", { exact: true }).fill("1");
    await prep.getByLabel("Garage remotes prepared", { exact: true }).fill("0");
    await prep.getByRole("button", { name: "Save resident codes", exact: true }).click();
    await expect(prep.getByRole("status")).not.toContainText("Unsaved");
    await expect.poll(async () => (await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json()).value.homeKeys).toBe("2");
    await send(tech, techHeaders, "PATCH", itemPath, { makeReadyStatus: "DONE" });
    await send(page, admin, "PATCH", itemPath, { paintStatus: "DONE", cleaningStatus: "DONE" });
    const inspector = await leasingContext.newPage();
    const inspectorHeaders = await login(inspector, staff[1].username, password);
    await inspector.getByRole("button", { name: /View:/ }).click();
    await inspector.getByTestId("tab-my-work").click();
    await inspector.getByTestId(`my-work-item-${item.id}`).getByRole("button", { name: "Inspect or hand off", exact: true }).click();
    await inspector.getByRole("button", { name: "Inspection details / report", exact: true }).click();
    const report = inspector.getByTestId("final-report-editor");
    await expect(report.locator('[data-testid^="final-report-result-"]')).toHaveCount(9);
    await expect(report.getByLabel("Home key count", { exact: true })).toHaveValue("2");
    await expect(report.getByLabel("Access fob count", { exact: true })).toHaveValue("1");
    await expect(report.getByRole("combobox", { name: /condensate/ })).toHaveCount(0);
    await report.getByTestId("final-report-date").fill("2026-09-15");
    await report.getByTestId("final-report-result-presentation-v2-3").selectOption("ATTENTION");
    await report.getByTestId("final-report-note-presentation-v2-3").fill("Touch up entry trim");
    await report.getByLabel("Internal follow-up for technician", { exact: true }).fill("Internal correction request");
    await report.getByRole("button", { name: "Save and send corrections to technician", exact: true }).click();
    await expect(report).toBeHidden();
    const returned = await (await tech.request.get(`${origin}/api${itemPath}`)).json();
    expect(returned).toMatchObject({ makeReadyStatus: "IN PROGRESS", paintStatus: "DONE", cleaningStatus: "DONE", completionStatus: "NO" });
    expect(JSON.stringify(await (await tech.request.get(`${origin}/api/notifications`)).json())).toContain("Final walk returned for corrections");
    const work = await (await tech.request.get(`${origin}/api/my-work`)).json();
    expect(work.items.some((row: any) => row.id === item.id)).toBe(true);
    let codes = await (await tech.request.get(`${origin}/api${itemPath}/resident-codes`)).json();
    expect(codes.readOnly).toBe(false);
    expect(codes.technicianFollowUp).toContain("Touch up entry trim");
    expect(codes.correctionPending).toBe(true);
    codes = await send(tech, techHeaders, "PUT", `${itemPath}/resident-codes`, { version: codes.version, value: { ...codes.value, technicianResolution: "Entry trim touched up and dry" } });
    expect(codes.correctionPending).toBe(false);
    await send(tech, techHeaders, "PATCH", itemPath, { makeReadyStatus: "DONE" });
    const assignment = await (await page.request.get(`${origin}/api${itemPath}/final-walk`)).json();
    expect(assignment.block.assignedUserId).toBe(staff[1].id);
    let data = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(data.draft.value.technicianResolution).toBe("Entry trim touched up and dry");
    for (const check of data.checks) data.draft.value.results[check.id] = { status: "CHECKED", note: "" };
    data.draft.value.handoffConfirmed = true;
    data.draft.value.gateCode = "RESIDENT-GATE";
    data.draft.value.pedestrianCode = "RESIDENT-WALK";
    data.draft.value.includeResidentCodes = true;
    // The inspector cannot overwrite preparation evidence supplied by the tech.
    data.draft.value.technicianResults = {};
    await send(inspector, inspectorHeaders, "PUT", `${reportPath}/items/${item.id}`, { version: data.draft.version, value: data.draft.value });
    data = await (await inspector.request.get(`${origin}/api${reportPath}?itemId=${item.id}`)).json();
    expect(Object.keys(data.draft.value.technicianResults)).toHaveLength(8);
    const preview = await send(inspector, inspectorHeaders, "POST", `${reportPath}/preview`, { itemId: item.id, settings: data.settings.value, draft: data.draft.value, format: "html" });
    expect(preview.html).toContain("RESIDENT-GATE");
    expect(preview.html).not.toContain("Internal correction request");
    expect(preview.html).not.toContain("Entry trim touched up and dry");
    const pdf = await send(inspector, inspectorHeaders, "POST", `${reportPath}/preview`, { itemId: item.id, settings: data.settings.value, draft: data.draft.value, format: "pdf" });
    expect((Buffer.from(pdf.pdfBase64, "base64").toString("latin1").match(/\/Type\s*\/Page\b/g) ?? []).length).toBe(1);
    await send(inspector, inspectorHeaders, "POST", `${itemPath}/mark-ready`, {});
    expect((await (await page.request.get(`${origin}/api${itemPath}`)).json()).completionStatus).toBe("YES");
    await inspector.screenshot({ path: testInfo.outputPath("final-walk-mobile.png") });
    await page.evaluate(() => { localStorage.setItem("makereadyos.themeMode", "dark"); localStorage.setItem("makereadyos.compactMode", "false"); });
    await page.reload();
    await expect(page.locator(".app-shell")).toHaveAttribute("data-theme", "dark");
    await expect(page.locator(".app-shell")).not.toHaveClass(/compact-mode/);
  } finally { await techContext.close(); await leasingContext.close(); }
});
