import assert from "node:assert/strict";
import test from "node:test";

test("closing without follow-up archives the request and preserves linked treatment history", async t => {
  process.env.DATABASE_URL = "postgresql://unused:unused@127.0.0.1:1/unused";
  process.env.ADMIN_USERNAME = "pest-test";
  process.env.ADMIN_PASSWORD = "Test-Only-Password!123";
  process.env.SESSION_COOKIE_SECRET = "test-only-session-secret-12345678901234567890";
  const { prisma } = await import("../lib/prisma.js");
  const { pestControlRoutes } = await import("./pestControl.js");
  const { default: Fastify } = await import("fastify");
  const stub = (delegate: any, key: string, fn: (...args: any[]) => unknown) => {
    const original = delegate[key]; delegate[key] = fn;
    t.after(() => { delegate[key] = original; });
  };
  let issue: any = { id: "issue", propertyId: "demo", makeReadyItemId: "turn", pestType: "Ants", status: "Open", isArchived: false };
  let treatedQuery: any;
  let turnUpdate: any;
  let listQuery: any;
  stub(prisma.pestIssue, "findUnique", async () => issue);
  stub(prisma.pestIssue, "update", async ({ data }) => (issue = { ...issue, ...data }));
  stub(prisma.pestIssue, "findMany", async query => { listQuery = query; return []; });
  stub(prisma.pestIssue, "count", async () => 0);
  stub(prisma.pestIssue, "findFirst", async query => { treatedQuery = query; return issue; });
  stub(prisma.makeReadyItem, "update", async query => { turnUpdate = query; return {}; });
  stub(prisma.pestIssueNote, "create", async () => ({}));
  stub(prisma.auditLog, "create", async () => ({}));
  const app = Fastify();
  app.decorateRequest("currentUser", null);
  app.addHook("onRequest", async request => { request.currentUser = { id: "tech", fullName: "Demo Tech", role: "TECH", propertyAccess: [{ propertyId: "demo" }] } as any; });
  await app.register(pestControlRoutes);
  t.after(() => app.close());
  const close = (followUpDate?: string) => app.inject({ method: "POST", url: "/pest/issues/issue/close", payload: { closingNotes: "Treated", treatmentDate: "2026-09-28", followUpDate } });
  const closed = await close();
  assert.equal(closed.statusCode, 200, closed.body);
  assert.equal(issue.status, "Closed");
  assert.equal(issue.isArchived, true);
  assert.equal(issue.archivedById, "tech");
  assert.ok(issue.archivedAt instanceof Date);
  assert.equal(issue.followUpRequired, false);
  assert.equal(turnUpdate.data.pestStatus, "TREATED");
  assert.deepEqual(treatedQuery.where.AND[0], { OR: [{ isArchived: false }, { status: "Closed" }] });
  const followUp = await close("2026-10-05");
  assert.equal(followUp.statusCode, 200, followUp.body);
  assert.equal(issue.status, "Needs Follow Up");
  assert.equal(issue.isArchived, false);
  assert.equal(issue.archivedAt, null);
  assert.equal(issue.closedAt, null);
  assert.equal(issue.followUpRequired, true);
  const filtered = await app.inject({ url: "/pest/issues?propertyId=demo&activeOnly=true&overdueOnly=true&q=Ants&makeReadyOnly=true&makeReadyItemId=turn" });
  assert.equal(filtered.statusCode, 200, filtered.body);
  assert.equal(listQuery.where.propertyId, "demo");
  assert.equal(listQuery.where.AND[2].status, "Needs Follow Up");
  assert.ok(listQuery.where.AND[2].followUpDate.lt instanceof Date);
  assert.equal(listQuery.where.makeReadyItemId, "turn");
  assert.equal(listQuery.where.isArchived, false);
  assert.equal(listQuery.where.AND.length, 3, "search, active and overdue constraints all retained");
  assert.equal((await app.inject({ url: "/pest/issues?propertyId=demo&archiveOnly=true" })).statusCode, 200);
  assert.equal(listQuery.where.isArchived, undefined);
  assert.deepEqual(listQuery.where.AND[0].OR, [{ isArchived: true }, { status: { in: ["Closed", "Cancelled", "Archived"] } }]);
  assert.equal((await app.inject({ url: "/pest/issues?propertyId=other&activeOnly=true" })).statusCode, 403);
});
